# Generated by Django 5.2.6 on 2025-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('languages', models.JSONField(default=list)),
                ('translations', models.JSONField(default=dict)),
                ('tone', models.CharField(default='neutral', max_length=50)),
                ('audio_files', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
